version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "CBenoit"
      - "pacmancoder"
    open-pull-requests-limit: 3
    groups:
      ironrdp:
        patterns:
          - "ironrdp*"
      patch:
        dependency-type: "production"
        update-types:
          - "patch"
      dev:
        dependency-type: "development"
