use crate::prelude::*;
use std::env;
use std::path::{Path, PathBuf};

const TARGET_FRAMEWORKS: &[&str] = &["net9.0", "net10.0"];

pub fn fmt(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-FORMATTING");

    let output = cmd!(sh, "dotnet format --verify-no-changes").ignore_status().output()?;

    if !output.status.success() {
        anyhow::bail!("Bad formatting, please run 'dotnet format'");
    }

    println!("All good!");

    Ok(())
}

pub fn get_target_arch() -> anyhow::Result<&'static str> {
    match env::consts::ARCH {
        "x86_64" => Ok("x64"),
        "aarch64" => Ok("ARM64"),
        _ => anyhow::bail!("Unsupported architecture: {}", env::consts::ARCH),
    }
}

pub fn get_dotnet_output_path(target_framework: &str) -> anyhow::Result<PathBuf> {
    let arch_folder: &str = get_target_arch()?;
    let build_config = "Debug";

    let output_path = Path::new("dotnet")
        .join("Devolutions.NowProto")
        .join("bin")
        .join(arch_folder)
        .join(build_config)
        .join(target_framework);

    Ok(output_path)
}

pub fn list_files_for_target_framework(sh: &Shell, target_framework: &str) -> anyhow::Result<()> {
    let build_path = get_dotnet_output_path(target_framework)?;
    if !build_path.exists() {
        anyhow::bail!("Expected build output directory does not exist: {:?}", build_path);
    }

    list_files(sh, build_path.to_str().unwrap()).context(format!(
        "failed to list artifacts generated by dotnet build ({})",
        target_framework
    ))?;
    Ok(())
}

pub fn build(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-BUILD");

    let platform = get_target_arch()?;
    cmd!(sh, "dotnet build -p:Platform={platform}").run()?;

    if is_verbose() {
        for &target_framework in TARGET_FRAMEWORKS {
            list_files_for_target_framework(sh, target_framework)?;
        }
    }

    println!("All good!");

    Ok(())
}

pub fn tests_run(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-TESTS-RUN");

    let platform = get_target_arch()?;

    cmd!(sh, "dotnet test -p:Platform={platform}").run()?;

    println!("All good!");

    Ok(())
}
