use crate::prelude::*;

pub fn fmt(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-FORMATTING");

    let output = cmd!(sh, "dotnet format --verify-no-changes").ignore_status().output()?;

    if !output.status.success() {
        anyhow::bail!("Bad formatting, please run 'dotnet format'");
    }

    println!("All good!");

    Ok(())
}

pub fn build(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-BUILD");

    cmd!(sh, "dotnet build").run()?;

    if is_verbose() {
        list_files(sh, "./nugets/Devolutions.NowProto/bin/Debug/net8.0")
            .context("failed to list artifacts generated by dotnet build")?;
    }

    println!("All good!");

    Ok(())
}

pub fn tests_run(sh: &Shell) -> anyhow::Result<()> {
    let _s = Section::new("DOTNET-TESTS-RUN");

    cmd!(sh, "dotnet test").run()?;

    println!("All good!");

    Ok(())
}
